// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifavpuosbnldxyglpmkp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmYXZwdW9zYm5sZHh5Z2xwbWtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNTM0OTAsImV4cCI6MjA3MTYyOTQ5MH0.FZEjNaPfcVIxv9wHm8k1WsQWToiWgqdi7XGvIy6_OS8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});